name: Cypress Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.1'

      - name: Install Cypress
        run: |
          npm install cypress@9.5.1

      - name: Run Cypress tests
        run: |
          npx cypress run
